### PR TITLE
Signature function failure fixed towards new instagram api sign guidelines.

### PR DESCRIPTION
**Pull request by onderceylan**
* Added ability to enforce all request to be signed.
* Signature method updated.

### CODE REVIEW

**Comment by ameykpatil** [comment]
Why is this not merged yet? Instagram has asked to use the enhanced method by September 1, 2015.

**Comment by n1t0** [comment]
Published as `0.5.8`. Sorry for the delay.

**Comment by camwes** [comment]
@n1t0 is there an example of how to use this correctly? I am getting `OAuthForbiddenException: Invalid signed-request: Missing required parameter 'sig'`

**Comment by tom2strobl** [comment]
Same here. One API flaw imho is that afaik you can't have an `access_token` and a `client_secret` in `my.auth` both at the same time. That means that you can't really make signed access_token requests. For now I just forked the lib and dirty-overrid that part. Not sure how to make a PR without breaking core functionality though.

**Pull request merged**
